################################################################################
# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################

application:
  enable-perf-measurement: 1
  perf-measurement-interval-sec: 5

tiled-display:
  enable: 1
  rows: 2
  columns: 2
  width: 1280
  height: 720
  gpu-id: 0
  #(0): nvbuf-mem-default - Default memory allocated, specific to particular platform
  #(1): nvbuf-mem-cuda-pinned - Allocate Pinned/Host cuda memory, applicable for Tesla
  #(2): nvbuf-mem-cuda-device - Allocate Device cuda memory, applicable for Tesla
  #(3): nvbuf-mem-cuda-unified - Allocate Unified cuda memory, applicable for Tesla
  #(4): nvbuf-mem-surface-array - Allocate Surface Array memory, applicable for Jetson
  ####################################################################################
  #(0): nvbuf-mem-default - 특정 플랫폼에 따라 할당된 기본 메모리
  #(1): nvbuf-mem-cuda-pinned - Pinned/Host cuda 메모리를 할당하며, Tesla에 적용 가능
  #(2): nvbuf-mem-cuda-device - Device cuda 메모리를 할당하며, Tesla에 적용 가능
  #(3): nvbuf-mem-cuda-unified - Unified cuda 메모리를 할당하며, Tesla에 적용 가능
  #(4): nvbuf-mem-surface-array - Surface Array 메모리를 할당하며, Jetson에 적용 가능
  ####################################################################################
  nvbuf-memory-type: 0


source:
 #<--
 # csv-file-path: sources_4.csv
 #---
 csv-file-path: sources_rtsp.csv
 #-->

#<--
# sink0:
#---
sink00:
#-->
  enable: 1
  #Type - 1=FakeSink 2=EglSink 3=File
  type: 2
  sync: 1
  source-id: 0
  gpu-id: 0
  nvbuf-memory-type: 0

#<--
# sink1:
#---
sink10:
#-->
  enable: 1
  #Type - 1=FakeSink 2=EglSink 3=File 4=UDPSink 5=nvdrmvideosink 6=MsgConvBroker
  type: 6
  #<--
  # msg-conv-config: dstest5_msgconv_sample_config.yml
  #---
  msg-conv-config: config-msgconv.yml
  #-->
  #(0): PAYLOAD_DEEPSTREAM - Deepstream schema payload
  #(1): PAYLOAD_DEEPSTREAM_MINIMAL - Deepstream schema payload minimal
  #(256): PAYLOAD_RESERVED - Reserved type
  #(257): PAYLOAD_CUSTOM   - Custom schema payload
  msg-conv-payload-type: 0
  msg-broker-proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_kafka_proto.so
  #Provide your msg-broker-conn-str here
  #<--
  # msg-broker-conn-str: <host>;<port>;<topic>
  # topic: <topic>
  #---
  msg-broker-conn-str: localhost;9092;prototype-events
  topic: prototype-events
  #-->
  #Optional:
  #msg-broker-config: ../../deepstream-test4/cfg_kafka.txt

#<--
# sink2:
#---
sink20:
#-->
  enable: 0
  type: 3
  #1=mp4 2=mkv
  container: 1
  #1=h264 2=h265 3=mpeg4
  ## only SW mpeg4 is supported right now.
  codec: 3
  sync: 1
  bitrate: 2000000
  output-file: out.mp4
  source-id: 0

osd:
  enable: 1
  gpu-id: 0
  border-width: 1
  text-size: 15
  text-color: 1;1;1;1
  text-bg-color: 0.3;0.3;0.3;1
  font: Arial
  show-clock: 0
  clock-x-offset: 800
  clock-y-offset: 820
  clock-text-size: 12
  clock-color: 1;0;0;0
  nvbuf-memory-type: 0

streammux:
  gpu-id: 0
  ##Boolean property to inform muxer that sources are live
  live-source: 0
  batch-size: 4
  ##time out in usec, to wait after the first buffer is available
  ##to push the batch even if the complete batch is not formed
  batched-push-timeout: 40000
  ## Set muxer output width and height
  width: 1920
  height: 1080
  ##Enable to maintain aspect ratio wrt source, and allow black borders, works
  ##along with width, height properties
  enable-padding: 0
  nvbuf-memory-type: 0
  ## If set to TRUE, system timestamp will be attached as ntp timestamp
  ## If set to FALSE, ntp timestamp from rtspsrc, if available, will be attached
  # attach-sys-ts-as-ntp: 1

primary-gie:
  enable: 1
  gpu-id: 0
  batch-size: 4
  ## 0=FP32, 1=INT8, 2=FP16 mode
  bbox-border-color0: 1;0;0;1
  bbox-border-color1: 0;1;1;1
  bbox-border-color2: 0;1;1;1
  bbox-border-color3: 0;1;0;1
  nvbuf-memory-type: 0
  interval: 0
  gie-unique-id: 1
  #<--
  # model-engine-file: ../../samples/models/Primary_Detector/resnet18_trafficcamnet.etlt_b4_gpu0_int8.engine
  # labelfile-path: ../../samples/models/Primary_Detector/labels.txt
  # config-file: ../../samples/configs/deepstream-app/config_infer_primary.yml
  # #infer-raw-output-dir: ../../samples/primary_detector_raw_output/
  #--- Use PeopleNet as PGIE
  model-engine-file: ../../prototype/models/peoplenet/resnet34_peoplenet_int8.etlt_b4_gpu0_int8.engine
  labelfile-path: ../../prototype/models/peoplenet/labels.txt
  config-file: ./config_infer_primary_PeopleNet+NvDCF.txt
  #config-file: ./config_infer_primary_PeopleNet+NvDeepSORT.txt
  #-->

#<--
# secondary-gie:
#---
secondary-gie00:
#-->
  enable: 1
  gpu-id: 0
  batch-size: 8
  operate-on-gie-id: 1
  operate-on-class-ids: 0
  gie-unique-id: 2
  config-file: ./config_infer_secondary_bodypose3dnet.txt

tracker:
  enable: 1
  # For NvDCF and NvDeepSORT tracker, tracker-width and tracker-height must be a multiple of 32, respectively
  tracker-width: 960
  tracker-height: 544
  ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
  # ll-config-file required to set different tracker types
  # ll-config-file: ../../samples/configs/deepstream-app/config_tracker_IOU.yml
  # ll-config-file: ../../samples/configs/deepstream-app/config_tracker_NvSORT.yml
  ll-config-file: ../../samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
  # ll-config-file: ../../samples/configs/deepstream-app/config_tracker_NvDCF_accuracy.yml
  # ll-config-file: ../../samples/configs/deepstream-app/config_tracker_NvDeepSORT.yml
  gpu-id: 0
  display-tracking-id: 1
